##############################################################
# Build that shit.
##############################################################
build:
  stage: build
  image: microsoft/dotnet:latest
  script:
    - dotnet restore
    - dotnet build -c Release
    - cd FsFirestore
    - dotnet pack -c Release -o ../package
  artifacts:
    paths:
      - ./package

##############################################################
# Running unit tests.
##############################################################
test/unit-testing:
  stage: test
  image: microsoft/dotnet:latest
  script:
    - echo $GCP > ./GCP.json
    - dotnet restore
    - dotnet build
    - cd FsFirestore.Tests
    - dotnet test

##############################################################
# Deployment.
##############################################################
deploy/nuget:
  stage: deploy
  image: microsoft/dotnet:latest
  only:
    - master
  script:
    dotnet nuget push ./package/*.nupkg -k $NUGET_API_KEY -s nuget.org
